//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SmartParkingSystemAPI
{
    using System;
    using System.Collections.Generic;
    
    public partial class ParkingSlotMaster
    {
        public int ID { get; set; }
        public int ParkSlotID { get; set; }
        public string SlotName { get; set; }
        public string Address { get; set; }
        public string BarcodeNo { get; set; }
        public Nullable<bool> IsOccupied { get; set; }
        public Nullable<int> OccupiedBy { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public Nullable<System.DateTime> ParkInTime { get; set; }
        public Nullable<System.DateTime> ParkOutTime { get; set; }
    }
}
